#!/bin/bash
bindir=$(dirname $0)
startdir=$(pwd)
echo "bindir: $bindir"
if test $# -eq 0 || test "$1" = "tests"
then
	base="$startdir/test"
else
	base="$startdir/$1"
fi
specs="${2:-$base/specs}"
data="${3:-$base/data}"

echo "raw -> csv" &&
nodejs $bindir/raw2csv.js -i "$data/raw" -o "$data/csv" -m "$specs/mappings.json" &&
echo "csv -> json" &&
nodejs $bindir/csv2json.js -i "$data/csv" -o "$data/json" -m "$specs/mappings.json"